language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:

- git push --delete origin gh-pages

- git branch -d gh-pages

- git checkout -b gh-pages

- ng build --prod --output-path legendoftamar --base-href="https://legendoftamar.github.io/legendoftamar/"

- sudo ngh --dir=/legendoftamar
